### PR TITLE
Unchaught Exception handling

### PR DESCRIPTION
**Pull request by ondrejvelisek**
+ add some czech translation

### CODE REVIEW

**Comment by zlamalp** [comment]
Hi, can you please rebase it on current master. Thanks.

**Comment by ondrejvelisek** [comment]
Done. There were only problem in translation files.

**Comment by zlamalp** [comment]
Hi, I don't think GUI freezes on all exceptions, maybe we should report only those exceptions in a popup window. Users doesn't like when they work is lost on page refresh if it's not necessary.

I'm missing stack trace info, which would be most usefull in finding where the bug really is. I don't think it's nice string to be passed in URL to the new page. I tested it in old GUI before ConcurrentModificationException bug was fixed. See ``zlamalp:exception`` branch.

We could log into browser console, where we could see the stacktrace from java. Just by adding this to gwt.xml file:
```xml
<inherits name="com.google.gwt.logging.Logging" />
<set-property name="compiler.useSourceMaps" value="true" />

<set-property name="gwt.logging.logLevel" value="SEVERE"/>
<set-property name="gwt.logging.enabled" value="TRUE"/>
<set-property name="gwt.logging.consoleHandler" value="ENABLED"/>
<set-property name="gwt.logging.systemHandler" value="ENABLED"/>
<set-property name="gwt.logging.developmentModeHandler" value="ENABLED"/>

<set-property name="compiler.stackMode" value="emulated" />
<set-configuration-property name="compiler.emulatedStack.recordLineNumbers" value="true"/>
<set-configuration-property name="compiler.emulatedStack.recordFileNames" value="true"/>
```
then in your PerunUncaughtExceptionHandler you can create root logger:

```java
private static Logger rootLogger = Logger.getLogger("");
```
and log into it when exception is caught:
```java
rootLogger.log(Level.SEVERE, "", t);
```
I know, it doubles app size, but I'm not sure it's a real problem now days. Then we can get something like this in a browser:

```
Tue Dec 01 12:10:55 GMT+100 2015 
SEVERE: java.util.ConcurrentModificationException
	at Unknown.fillInStackTrace_0_g$(Throwable.java:116)
	at Unknown.Throwable_1_g$(Throwable.java:55)
	at Unknown.Exception_1_g$(Exception.java:25)
	at Unknown.RuntimeException_1_g$(RuntimeException.java:25)
	at Unknown.ConcurrentModificationException_1_g$(ConcurrentModificationException.java:25)
	at Unknown.checkStructuralChange_0_g$(ConcurrentModificationDetector.java:36)
	at Unknown.next_17_g$(AbstractHashMap.java:101)
	at Unknown.next_16_g$(AbstractHashMap.java:100)
	at Unknown.next_19_g$(AbstractMap.java:220)
	at Unknown.execute_40_g$(UiElements.java:1828)
	at Unknown.$executeRepeating_0_g$(SchedulerImpl.java:46)
	at Unknown.runScheduledTasks_0_g$(SchedulerImpl.java:179)
	at Unknown.flushPostEventPumpCommands_0_g$(SchedulerImpl.java:347)
	at Unknown.execute_5_g$(SchedulerImpl.java:78)
	at Unknown.execute_4_g$(SchedulerImpl.java:141)
	at Unknown.apply_0_g$(Impl.java:247)
	at Unknown.entry0_0_g$(Impl.java:299)
	at Unknown.anonymous(Impl.java:72)
```
Please try to discover, how to get this stacktrace, so we could send it in bug report. For now, I suggest you add above at least for dev version of build. Also please add support for this to all wui apps. Thank you.

**Comment by zlamalp** [comment]
Hi, I implemented it already. It's on current master for now. Closing this pull request.

**Pull request closed without merging**
